[package]
name = "hledger_helper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
csv = "1.3.0"
serde = { version = "1.0.203", features = ["serde_derive"] }
time = "0.3.36"
